.github/workflows/ci.yml
Already install in the ubuntu-20.04 image
See https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu2004-README.md
=> Don't install awscli in GitHub action

scripts/deploy_to_s3.sh
This reverts commit e7d047bd67435e11932a7c85e444672403b90258.
=> Revert "Don't upload robots.txt to production"

src/KeyboardNavigation.js
To test:
* press arrow up key
* press ctrl key
* release arrow up key
* release ctrl key
The navigation should stop.
=> Always stop keyboard navigation on keyup

src/areaOfInterest/areaOfInterestTemplate.js, src/draw/CesiumDraw.js, src/draw/helpers.js, src/utils.js
Area calculation fixed: https://i.imgur.com/pfcfjtH.png (for rectangle area calculation now uses the same function as for polygon)
=> Improve the AOI area calculation

README.md, src/constants.js, src/viewer.js
TODO: wait for official swisstopo terrain URLs.
=> Chtopo terrain as default

src/viewer.js
This fixes the VIP blocked terrain issue
=> use non priviledged terrain from swisstopo

src/index.js
- SSE=10000
- SSE=2 / timeout 5s
- remove loading indicator and add layers, lava, ...
=> 3 steps loader:

src/layers/ngm-layers-item.js
Won't work if the label has a space in it
=> Don't use layer label in the id

package-lock.json, package.json
=> Revert "Bump @rollup/plugin-commonjs from 16.0.0 to 17.0.0"

package-lock.json, package.json, src/auth.js, src/download.js, src/index.js, src/layertree.js, test/auth.test.js, test/download.test.js
This is the low level functions for downloading source data, filtering it geographically based on bbox (everythin inside or crossing the bbox should be kept), and creating a zip file.
Some tests were added too!
UI buttons, getting the bbox, calling the function with active layers and downloading the generated zip is to be done in a different PR.
=> Filter download data UI side

src/drop.js, src/ngm-app.js, src/toolbox/AreaOfInterestDrawer.js
=> Allow kml and gpx import with drag and drop into the map

src/constants.js
as far as tested, this seems to fix the CORS (or generally the swissforage) issue!
=> GSNGM-514 fix the URL for dev.swissforages.ch

src/constants.js
... I forgot that part: we can already use the prod URL of swissforages!
=> GSNGM-514 switch swissforages URL to prod

src/layertree.js
... and set the pickable to false for point cloud layer
=> GSNGM-570 Change the geocatID of boreholes

src/query/ObjectSelector.js
Fix for this comment: https://jira.camptocamp.com/browse/GSNGM-571?focusedCommentId=215774&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-215774
PS: It is ugly and slow, however works.
=> Fix earthquake highlight

locales/app.de.json, locales/app.en.json, locales/app.fr.json
@eleu 
I did the translation (only layername of the earthquake > 3).
=> 2021.10 translation

README.md, src/viewer.js
Opt-in
Should help hotjar recording
=> Allow copying canvas content

locales/app.de.json, locales/app.en.json, locales/app.fr.json
=> 2021.10bis

src/style/layers.css
Hide/grey out kml upload layer action menu until further ui/ux specification take place
=> Grey out action menu for kml layers

locales/app.de.json, locales/app.en.json, locales/app.fr.json, locales/app.it.json, src/elements/draggable.ts, src/ngm-app.ts, src/style/index.css, src/style/ngm-map-chooser.css, src/style/ngm-side-bar.css
fixes:
- https://jira.camptocamp.com/browse/GSNGM-745
- https://jira.camptocamp.com/browse/GSNGM-752
=> Add contact link inside the map container

locales/app.de.json, locales/app.en.json, locales/app.fr.json, locales/app.it.json, src/elements/ngm-cam-configuration.ts, src/ngm-app.ts, src/notifications.ts, src/style/index.css, src/style/ngm-cam-configuration.css, src/toolbox/ngm-geometry-edit.ts
=> Show snackbar regarding the z / angle / pitch / coordinates fixation when a user closes the camera panel

.github/workflows/ci.yml, .storybook/main.cjs, package.json, src/stories/Layers.stories.ts
This reverts commit feda1d22ddd99ed86eaeb977b46b3b45ce5365de.
=> Storybook for data (moved from https://github.com/swissgeol/ngm/pull/753)

src/elements/ngm-height-slider.ts, src/test/ngm-height-slider.test.ts
Comment is right, code is wrong
=> Fix typo in height to value function

src/layers/ngm-layers-upload.ts
=> Use query decorator

api/.env, api/Cargo.lock, api/Cargo.toml, api/src/handlers.rs, api/src/lib.rs, api/src/main.rs, api/tests/basic.rs
TODO: Need to solve how we will add AWS creds.
=> Duplicate a topic to a project - Backend

api/.env, api/Dockerfile, api/DockerfileDev, docker-compose.yaml
=> fix api build & local dev

api/Cargo.lock, api/Cargo.toml, api/src/error.rs, api/src/lib.rs
=> Bump axum & tower-http

ui/src/constants.ts, ui/src/elements/hide-overflow.ts, ui/src/elements/ngm-dashboard.ts, ui/src/elements/ngm-side-bar.ts, ui/src/style/ngm-dashboard.css, ui/src/style/ngm-side-bar.css
The limit is now how many can be fitted in one line
=> Display max of projects in a line and hide overflowed

ui/src/query/ObjectSelector.js, ui/src/query/QueryManager.js, ui/src/query/objectInformation.js
The deprecated function was removed from cesium in version 1.98
=> Use getPropertyIds instead of getPropertyNames

ui/locales/app.de.json, ui/locales/app.en.json, ui/locales/app.fr.json, ui/locales/app.it.json
"hotjar" delted from app.de, app.fr, app.en, app.it
=> 2023.04 05 update locales

ui/src/viewer.ts
New terrain as default terrain integrated.
The "cli_terrein_ch-2m" should be available by URL parameter.
=> New swisstopo terrain

.github/workflows/ci.yml
=> chore: update cypress-io/github-action

ui/cypress/e2e/toolbox.cy.ts, ui/src/style/ngm-side-bar.css, ui/src/style/ngm-toolbox.css, ui/src/style/variables.css, ui/src/toolbox/ngm-geometries-simple-list.ts
Updated styles to scroll only on the geometries list and not on the whole panel
=> Update scroll for geometries panel

ui/src/elements/ngm-voxel-filter.ts, ui/src/elements/ngm-voxel-simple-filter.ts, ui/src/layers/voxels-helper.ts
`u_filter_min` and `u_filter_max` replaced with `u_min` and `u_max` to make filtering for temperature model works
=> Fix simple voxel filtering

ui/src/elements/ngm-side-bar.ts, ui/src/layers/ngm-catalog.ts, ui/src/layers/ngm-layers-item.ts, ui/src/layertree.ts, ui/src/search.js
- Added ngm-int-privileged and ngm-dev-privileged groups for boreholes
- Made support of multiple user groups for layers
=> Added dev int user groups and support for multiple groups

ui/src/elements/dashboard/ngm-dashboard.ts, ui/src/elements/ngm-side-bar.ts, ui/src/ngm-app.ts, ui/src/style/header.css, ui/src/style/icons.css, ui/src/style/index.css, ui/src/style/ngm-side-bar.css, ui/src/style/search.css, ui/src/style/variables.css
- Login and language switch moved to the header
- Topics hidden
- Removed labels from the left sidebar
=> GSNGM-1174 + GSNGM-1171 Move buttons, modify navigtion rail

ui/src/elements/ngm-cam-configuration.ts, ui/src/elements/ngm-minimap.ts, ui/src/viewer.ts
Fixed:
1. Changing pitch modifies azimuth
2. Camera position on minimap
Updated:
1. Made angle configuration from 0 to 359 degrees
=> Camera panel fixes

ui/src/viewer.ts
=> Set limits active as default

ui/src/auth.ts, ui/src/layers/helpers.ts, ui/src/ngm-app.ts, ui/src/slicer/SlicingLine.ts
=> Remove console logs

api/src/database.rs, ui/Dockerfile, ui/index.html, ui/src/earthquakeVisualization/earthquakeVisualizer.js, ui/src/elements/dashboard/ngm-dashboard.ts, ui/src/elements/ngm-layer-legend.ts, ui/src/elements/ngm-minimap.ts, ui/src/elements/ngm-object-information.ts, ui/src/elements/ngm-share-link.ts, ui/src/ngm-app.ts, ui/src/query/SwisstopoIdentify.ts, ui/src/search.js, ui/src/style/index.css, ui/src/style/layers.css, ui/src/style/ngm-action-list-item.css, ui/src/style/ngm-cam-configuration.css, ui/src/style/ngm-checkbox.css, ui/src/style/ngm-cursor-information.css, ui/src/style/ngm-dashboard.css, ui/src/style/ngm-geometry-info.css, ui/src/style/ngm-input.css, ui/src/style/ngm-layer-legend.css, ui/src/style/ngm-point-edit.css, ui/src/style/ngm-share-link.css, ui/src/style/ngm-side-bar.css, ui/src/style/ngm-toolbox.css, ui/src/style/search.css, ui/src/toolbox/ngm-geometry-info.ts, ui/webpack.config.js
=> Fix: sonar cloud quick fixes

ui/src/components/core/core-button.ts, ui/src/components/core/core-icon.ts, ui/src/components/layer/layer-tabs.ts, ui/src/styles/index.css, ui/src/styles/theme.ts
Adds styles (Colors, Typography, Effects and Animations) according to Figma.
The styles are not yet used anywhere, with the exception of the `ngm-core-button`, which has been fully styled according to the Figma.
=> Feature: Figma Styles

ui/src/toolbox/GeometryController.ts
=> Fix 1429: Geometriebearbeitung aufarbeiten.

ui/src/components/core/core-button.ts, ui/src/components/core/core-modal.ts, ui/src/components/layout/layout-consent-modal.ts, ui/src/elements/ngm-cursor-information.ts, ui/src/elements/ngm-side-bar.ts, ui/src/ngm-app.ts
=> Feature 1428: Sammeltask kleine Frontendanpassungen

ui/src/components/core/core-button.ts, ui/src/components/layer/display/layer-display-list-item.ts
Fix cursor not showing dragging icon while a layer item is being reordered.
=> Fix: Layer Grab Indicator

ui/src/components/layer/layer-panel.ts
Fixes the layer catalog not taking up as much space as available, effectively leaving half of the sidebar empty when no additional layers are selected.
=> Fix: Layer Catalog Height

.github/workflows/deploy.yml
=> Feature 1426: Deployment auf INT

ui/src/components/navigation/navigation-search.ts
=> Feature 1436: Suche anpassen | Fly-to entfernen

ui/src/toolbox/GeometryController.ts
=> Fix 1395: Kopierte Geometrie ist an Original geknüpft

ui/src/features/layer/display/layer-display-list-item.element.ts
=> Feature 1475: Fix time travel being shown for layers with only a single time entry.

api/Cargo.toml, api/src/lib.rs, ui/Dockerfile, ui/nginx.conf
=> security headers

ui/package-lock.json, ui/package.json
=> revert cesium back to 1.123.1 due to breaking change in 1.127

ui/src/elements/dashboard/ngm-add-member-form.ts
=> add missing import

k8s/templates/deployment.api.yaml
=> Feature 1488: DEV- und INT-Banner integrieren

ui/src/layertree.ts
Hi @daniel-va 
wie besprochen hier der PR mit den ausgeschalteten Voxel-Daten. Danke für dein Review. Wenn ok, kann du den PR direkt mergen.
=> voxel-data Rheintal temporarilly switched off

ui/src/layertree.ts
Hallo zusammen
Kann von euch jemand den PR prüfen.
Ich habe heute die Integration der daten besprochen. Weir können sie auf dev deployen.
Wenn der PR ok für euch, bitte direkt mergen.
Danke und Gruss
=> voxeldata activated

ui/src/elements/ngm-minimap.ts
=> Bugfix 1520: Minimap / Kameraicon nicht korrekt

.github/ISSUE_TEMPLATE/1-issue.md, .github/ISSUE_TEMPLATE/2-bug.md
=> Copy issues templates from assets

ui/src/elements/ngm-side-bar.ts
=> Show number of all geometries, not just visible ones

ui/locales/app.de.json, ui/locales/app.en.json, ui/locales/app.fr.json, ui/locales/app.it.json
Ich hab noch das Naming des Rheintal Layers angepasst. Wäre gut, wenn wir das noch in den Release aufnehmen könnten.
=> Translations Rheintal naming

ui/src/elements/ngm-ion-modal.ts
=> Fix icon scroll behavior and overflow of modal

k8s/templates/ingress-route.yaml
=> Remove api from path

ui/src/api/client-config.ts, ui/src/elements/ngm-side-bar.ts, ui/src/features/navigation/navigation-search.element.ts, ui/src/layertree.ts, ui/src/ngm-app.ts
Resolves #1465.
Hides the swissBEDROCK layer on INT and PROD, as the layer should not yet be publicly available.
=> Feature 1465: Integration swissBEDROCK

ui/src/ngm-app.ts
=> Feature 1600: Google Analytics auf DEV und INT deaktivieren

ui/locales/layers/layers.de.json, ui/package.json, ui/src/features/core/core-radio.element.ts, ui/src/features/core/core-window.element.ts, ui/src/features/layer/layer.module.ts, ui/src/features/layer/tiff/layer-tiff-bands.element.ts, ui/src/features/layer/tiff/layer-tiff-legend.element.ts, ui/src/features/layer/tiff/layer-tiff.controller.ts, ui/src/layertree.ts, ui/src/utils/fn.utils.ts, ui/tsconfig.json
=> Feature 1595: swissBEDROCK | Dynamische Legende

ui/src/features/core/core-radio.element.ts, ui/src/features/layer/info/layer-info-item.element.ts, ui/src/features/layer/tiff/layer-tiff-bands.element.ts
=> Feature 1599: Design Infobox

ui/locales/app/app.de.json, ui/locales/app/app.en.json, ui/locales/app/app.fr.json, ui/locales/app/app.it.json
@daniel-va 
Tooltip of 2D/3D-mode changed
#1642
=> Tooltips 2D-mode changed

ui/src/features/layer/layer.service.ts, ui/src/features/layout/layout-cursor-info.element.ts
Fixes some general behavior of voxel layers (removal of active layers, display of coordinates).
=> Bugfix: Voxel Layer Behavior

ui/cypress/e2e/layers/change-background.feature, ui/cypress/e2e/navigation/search.feature, ui/cypress/e2e/navigation/search/search.ts, ui/src/features/navigation/navigation-search.element.ts
=> Bugfix 1632: Suche nach Swissgeol Layern
