swisstopo/swissgeol-viewer-suite

- src/elements/ngm-feature-height.js
`getHeight` can return `undefined` and `NaN` is displayed
> Avoid NaN height in ngm-feature-height

- README.md
- src/index.js
Some Swisstopo terrain is broken.
CesiumJS gets stuck while trying to upscale it.
To reproduce:
- open http://localhost:8000/?initialScreenSpaceError=20
- the loading screen stays displayed forever.
To workaround use Cesium terrain:
- open http://localhost:8000/?initialScreenSpaceError=20&ownterrain=false
- it works
> Allow to reproduce app stuck loading issue

- src/draw/CesiumDraw.js
As advised by the API documentation:
https://cesium.com/docs/cesiumjs-ref-doc/Scene.html?classFilter=scene#pickTranslucentDepth
> Render scene before calling pickPosition

- Makefile
Otherwise the deploy_to_s3 script fails
> Run build-storybook in the dist target

- ui/src/elements/ngm-layer-legend.ts
Line 66 ,modified, because structure of geocat.ch-URL changes as documented here: https://github.com/geoadmin/geocat/wiki/CHANGELOG-V3.x-to-V4.x-(for-users)
> Change geocat-URL

- ui/src/elements/ngm-side-bar.ts
- ui/src/layers/ngm-layers-item.ts
- ui/src/layers/ngm-layers.ts
Besides the issue mentioned in the ticket, this PR also fixes:
- Opacity bar not displayed on initial load for two default displayed layers (cross section and borehole) 
- Some layers have NaN% as label for the opacity (e.g. Temperatures - Horizon (TUMa))
> Fix data catalog / layers display interactions

- ui/src/layers/ngm-catalog.ts
- ui/src/layertree.ts
The boreholes shall be accessible only for users in the "ngm-prod-privileged"-group. After re-integration of boreholes it will accessable publicly.
cf. GSNGM-1156
> Update layertree.ts - Make public boreholes private

- ui/src/images/i_info.svg
- ui/src/style/icons.css
- ui/src/style/ngm-toolbox.css
- ui/src/toolbox/data-download.ts
- ui/src/toolbox/ngm-draw-section.ts
- ui/src/toolbox/ngm-measure.ts
- ui/src/toolbox/ngm-slicer.ts
Would it be better to keep the icon and its styling, even if it's not used anymore ? I splitted the PR in two commits, delete the second one to keep the icon in the project.
> GSNGM-896: remove "i" icon in toolboxes

- ui/src/cesiumutils.ts
- ui/src/elements/ngm-coordinate-popup.ts
- ui/src/elements/ngm-cursor-information.ts
- ui/src/elements/ngm-map-configuration.ts
- ui/src/elements/ngm-nav-tools.ts
- ui/src/store/navTools.ts
- Added a new subject in the store to notify about exaggeration change
- Added calculations to shift the camera and target point on exaggeration change.
- Updated the `positionFromPxDistance` function to calculate z-axis positions too. Before, the z-axis was calculated from the x-axis and was drawn wrong when exaggeration was applied. 
- Height in cursor position information divided on vertical exaggeration to have the same height at a position when exaggeration is applied.
> Update camera, target point positions and cursor height information on exaggeration

- ui/src/elements/ngm-side-bar.ts
- ui/src/layers/LayersActions.ts
Made ordering between uploaded KMLs work
1. Fixed ordering in the layers list by adding the `layer` property for uploaded layers
2. Added sorting in the viewer dataSources
> Ordering for uploaded KMLs

- .github/workflows/ci.yml
- DEPLOY_VIEWER.md
- Makefile
- docker-compose-tests.yaml
- docker-compose.yaml
- scripts/deploy-to-env.sh
- scripts/deploy_viewer.sh
- scripts/release_api.sh
1. Updated name for API docker image from docker hub one (camptocamp/swissgeol_api) to github repository (ghcr.io/swisstopo/swissgeol-viewer-app-api)
2. Updated readme
> Use github repository to store Docker images

- ui/src/style/index.css
"bottom" for disclaimer-link class changed to 20px. IT-text overplapped contact-link
https://camptocamp.atlassian.net/browse/GSNGM-1203
> Reduce bottom-rule for disclaimer-link

- ui/src/elements/ngm-side-bar.ts
resolves #1348 
To test, use this [Link](http://localhost:8000/?lang=de&lon=7.99597&lat=46.87756&elevation=425658&heading=0&pitch=-90&map=ch.swisstopo.pixelkarte-grau&map_transparency=0.00&layers=ch.swisstopo.geologie-geocover%2Cch.swisstopo.swissalti3d-reliefschattierung%2Cch.swisstopo.geologie-geophysik-geothermie&layers_visibility=true%2Ctrue%2Ctrue&layers_transparency=0.00%2C0.00%2C0.00&layers_timestamp=current%2Ccurrent%2Ccurrent&maximumScreenSpaceError=4) 
This is based on #1353 and should thus be reviewed after it has been merged
> Fix 1348: Layerrreihenfolge nach Reload

- ui/src/draw/CesiumDraw.ts
Resolves #1349 
This is based on #1353  and should thus be reviewed after it has been merged
> Fix 1349:  Geometry Edit Freeze

- k8s/templates/deployment.api.yaml
- k8s/values.template.yaml
Add `gst_url` to k8s deployment
> Fix: Missing GST URL

- ui/src/toolbox/ngm-gst-interaction.ts
Resolves #1341.
Ensures that the GST PDF download url always uses HTTPS.
> Feature 1341: Neue GST Url

- ui/src/features/core/base/core-base-popup.element.ts
Fixes an issue where translated text within popups is not updated when changing between languages.
This was caused by Lit not supporting manually moving dynamically generated text nodes.
When updating such a node, Lit expected it to be at its original place, which caused an error.
The fix for this is that we now just clone text nodes into popups instead of moving them, which solves this issue, while still keeping reactivity intact.
> Feature 1474: Übersetzungen aktuelle Entwicklungen

- ui/src/features/core/base/core-base-popup-box.element.ts
- ui/src/features/core/base/core-base-popup.element.ts
- ui/src/features/core/core-dropdown.element.ts
- ui/src/features/core/core-element.element.ts
- ui/src/features/core/core-tooltip.element.ts
- ui/src/features/core/index.ts
- ui/src/features/layer/display/layer-display-list-item.element.ts
- ui/src/features/layer/display/layer-display-list.element.ts
Fixes an issue where translations in dropdowns was not being updated.
The problem was that the dropdowns were within a draggable element, which, after having been moved, caused the dropdown to loose its reactivity.
Also solves the issue where dropdowns were sometimes losing their content.
This had a similar reason, as Lit removed and re-added some elements containing dropdowns,
which destroyed the contents.
> Fix translated text in dropdowns not being updated

- api/.env
- api/src/config.rs
- ui/src/api/client-config.ts
- ui/src/features/layout/layout-version-tag.element.ts
- ui/src/features/layout/layout.module.ts
- ui/src/ngm-app.ts
Resolves #1434.
Note that the build workflows already fully support the `APP_VERSION` environment variable, so no change is needed there.
> Feature 1434: Versions-nr. im Header anzeigen

- .github/scripts/wait_for_service.sh
- docker-compose.yaml
Due to this repository being renamed, the name of Docker services being started inside of GitHub Actions have changed to being prefixed by `swissgeol-viewer-suite` insteadof ``swissgeol-viewer-app`. This now causes the API Test job in the [Code Quality Workflow](https://github.com/swisstopo/swissgeol-viewer-suite/actions/workflows/code-quality.yml) to fail.
This PR fixes this issue. Note that after this change has been merged, every currently open PR should be rebased onto `develop` so its checks can run through before being merged.
> Fix: Healthcheck in GH workflow

- ui/package-lock.json
- ui/package.json
- ui/src/style/index.css
- ui/vite.config.ts
Components from `swissgeol-ui-core` are loaded dynamically at runtime. Our build process didn't account for this, resulting in them not being included in the build process. This PR fixes this by adding a configuration to Vite which includes these files.
Additionally, the PR removes some of the fonts that have been superseded by the core library.
> Fix: Add ui core components to build output

- ui/package-lock.json
- ui/package.json
- ui/src/elements/ngm-voxel-filter.ts
Fixes bug where filter could not be opened again after closing for rheintal because of null value for input checkbox
> Handle nullable input selector

- ui/src/layers/voxels-helper.ts
- ui/src/layertree.ts
Resolves #1528.
Hides `undefined` values and its filter on the Rheital voxel layer.
> Feature 1528: voxel Rheintal - Anpassungen Filter und Tooltip

- ui/src/elements/ngm-nav-tools.ts
Resolves #1531.
*Don't merge this until a release candidate for 1.1.0 has been released!*
Removes the animated zoom when activating or moving the target point.
I'm actually pretty sure that the current, faulty behavior was intended by the previous developers, but did stop working at some point. The faulty code has not been changed in a while, and seems to have been "fixed" due to us changing something else somewhere else - I have not clue what, though.
With this PR, the behavior has been fully removed and won't appear anymore.
> Bug: Aktivierung des Targetpoints zoom auf die gesamte Schweiz

- ui/src/elements/ngm-nav-tools.ts
The target point anchor is currently not working - the camera doesn't rotate around it, so it is essentially useless. As discussed with @nOester, we remove the tool from the UI and will attempt a full bugfix for the next release.
> Disable target point tool

- k8s/templates/ingress-route.yaml
- k8s/templates/middleware.titiler.yaml
Resolves #1465.
Fixes the routing of the new `titiler` service in k8s.
> Feature 1465: Integration swissBEDROCK.

- .scrum
Ich glaube, dass wir dieses file nicht brauchen.
Wie sieht es mit 
- https://github.com/swisstopo/swissgeol-viewer-suite/tree/develop/.idea
- https://github.com/swisstopo/swissgeol-viewer-suite/tree/develop/.vscode
aus?
> remove .scrum

- ui/src/features/layer/tiff/layer-tiff.controller.ts
Resolves #1465.
Fixes an issue where the geoTIFF picker request was always using TiTiler's localhost address instead of the environment-specific one.
> Feature 1465: Integration swissBEDROCK

- ui/cypress/e2e/controls/control-2d.feature
- ui/src/features/controls/controls-2d-action.element.ts
- ui/src/features/controls/controls/control2d.controller.ts
Resolves #1630.
- Switches the 3d and 2d icon.
- Fixes an issue where camera tilting was no longer working correctly after toggling into 2d and back.
> Feature 1630: Icon von 2D/3D-Modus ändern

- ui/src/features/layer/display/layer-display-list-item.element.ts
- ui/src/features/layer/info/layer-info.service.ts
- ui/src/features/layer/tiff/layer-tiff.controller.ts
- ui/src/layertree.ts
Resolves #1648.
Fixes an issue where rounding of the geoTIFF metadata resulted in highlights not being calculated correctly. This has now been fixed by dynamically loading and calculating the metadata via TiTiler.
> Feature 1648: swissBEDROCK - Korrektur und Ergänzung Farbskala

- ui/src/layertree.ts
@daniel-va 
Dieser Layer kann nicht angezeigt werden und wird durch unseren Erdbeben-Layer ersetzt. daher habe ich ihn aus dem Layertree entfernt.
danke für dein review. Wenn ok, kannst du den PR direkt mergen.
> Layer "aktuelle Erdbeben" excluded

- ui/locales/app/app.it.json
Es gab noch ein "To_BE_TRANSLATED". das ist nun übersetzt.
Danke für dein Review
> TO_TRANSLATED translated

- ui/src/toolbox/GeometryController.ts
Resolves #1659.
Allows line drawings to once again clamp to the ground.
> Bugfix 1659: Zeichnen auf Objekten

- ui/src/features/layer/tiff/layer-tiff.controller.ts
Resolves #1656.
Thanks to @nOester local stack trace, I _think_ I got the error.
What I'm assuming is happening:
1. The tiff's band is switched.
2. This removes the active and adds a new one.
3. Before the new one is fully added, the band is switched again.
4. This causes the already removed band to be removed again, triggering an error.
The fix is now to not remove the band imagery if it cannot be found in the active imagery list, which is a check we have to do anyways.
> Bugfix 1656: swissBEDROCK | Bandwechsler blockiert
